Hook-up primo central repository to the catalog. (#300)
* [WIP] - Add Primo Central repository

* [WIP] Response not mapped properly

* [WIP ]Fixing up the models

* Working through the response

* [ WIP ] One Facet Working

* [WIP] watch me wip, watch me..

* Apply rubocop changes.

* Use to_hash without check.

`params.to_hash` benchmarks faster than:
`params.to_hash unless params.is_a? Hash`

```
irb(main):012:0> a = { a: 1, b: 2, c: 3 }
=> {:a=>1, :b=>2, :c=>3}
irb(main):013:0> Benchmark.bm { |bm| bm.report { iterations.times { a.to_hash } } }
       user     system      total        real
   0.000000   0.000000   0.000000 (  0.007689)
=> [#<Benchmark::Tms:0x007ff4ad25f108 @label="", @real=0.007688999990932643, @cstime=0.0, @cutime=0.0, @stime=0.0, @utime=0.0, @total=0.0>]
irb(main):014:0> Benchmark.bm { |bm| bm.report { iterations.times { a.to_hash unless a.i
s_a?(Hash) } } }
       user     system      total        real
   0.010000   0.000000   0.010000 (  0.008673)
=> [#<Benchmark::Tms:0x007ff4ad1fcbe8 @label="", @real=0.008673000033013523, @cstime=0.0, @cutime=0.0, @stime=0.0, @utime=0.009999999999999981, @total=0.009999999999999981>]
```

* Fix error: undefined method `each' for nil:NilClass`

* Enable paginator and facets search.

* Add correct search field.

* Hook up facets and document fields.

REF BL-185, BL-348, BL-349

* Fix bento missing advanced search link.

* Use orig title if supplied.

Fixes unexpected title features test error.

* config vid and scope.

* Revert "config vid and scope."

This reverts commit a277954539dfaa553680bc9e9fbf30fa51128a79.

Getting error when I set scope to default_scope

* Add vid and scope initializers

* Don't use ghost branch of primo gem

* Fix nav bar search form path

* Rubocop :exclamation:

* Fix specs for search url